pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'building stage...'
                
                bat 'npm install gh-pages --save-dev'
                bat 'npm run build'                

                echo 'building stage end...'
            }
        }

        stage('Deploy') {
            echo 'Deploying stage...'
            
            echo 'Deploying stage end...'
        }
        
    }
}
