pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'building stage...'
                
                bat 'npm install'
                bat 'npm run build'

                bat 'cd build'

                bat 'git init'
                bat 'git remote add github https://github.com/bear157/simple-node-js-react-npm-app.git' || true
                bat 'git branch -r'
                bat 'git checkout gh-pages'

                echo 'building stage end...'
            }
        }
        
    }
}
